# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 318c1515874b43670180423a04c5ba00dae6501ed0280ebe99ac112fe0b6e953de5d1b01cd6dc76605ffb4fbb6dab3096a972935c7c4f1a3f8b1b7a95ee53d8b

test:
  secret_key_base: 066f7357b0c6f7ca285312eb4eeea2bd11b43eee8ed0a2390c9edef0046ab759924ec147007fdca2bce9b78dea495c9292323bda00b7b0ad2a18641cac86c82b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
